---

- name: Create Docker volume for Media
  docker_volume:
    name: "{{ jellyfin_volume_name }}"
    driver_options: "{{ jellyfin_volume_driver_options }}"

- name: Ensure Jellyfin host config path exists
  file:
    path: "{{ jellyfin_config_host_path }}"
    state: directory 

# - name: Ensure Jellyfin config files are synchronised
#   copy:
#     src: "{{ jellyfin_remote_config_backup_src }}"
#     dest: "{{ jellyfin_config_host_path }}"
