---

- name: Mount up device by UUID
  mount:
    path: "{{ media_host_mount_point }}" 
    src: UUID="{{ media_disk_uuid }}"
    fstype: ext4 
    opts: noatime
    state: mounted

# - name: Create Docker NFS volume for Media
#   docker_volume:
#     name: "{{ jellyfin_volume_name }}"
#     driver_options: "{{ jellyfin_volume_driver_options }}"

- name: Ensure Jellyfin host config path exists
  file:
    path: "{{ jellyfin_config_host_path }}"
    state: directory 
    recurse: yes
    owner: "{{ container_user }}"
    group: "{{ container_user }}"


- name: Ensure jellyseerr host config path exists
  file:
    path: "{{ jellyseerr_config_host_path }}"
    state: directory 
    # recurse: yes
    # owner: "{{ container_user }}"
    # group: "{{ container_user }}"

# - name: Ensure Jellyfin config files are synchronised
#   copy:
#     src: "{{ jellyfin_remote_config_backup_src }}"
#     dest: "{{ jellyfin_config_host_path }}"
