---
- name: Ensure Jellyfin is created and started
  docker_container:
    name: "{{ jellyfin_container_name }}"
    image: "{{ jellyfin_container_image }}"
    volumes: "{{ jellyfin_volumes_full_paths }}" 
    # network_mode: host
    published_ports: "{{ jellyfin_container_port_bindings }}"
    networks:
      - name: "{{ media_server_docker_network }}"
    restart_policy: always
    state: started 



