---
 - import_tasks: base.yml 
   tags:
     - setup-all
     - setup-jellyfin
     - setup-jellyseerr
     - setup-base

 - import_tasks: install.yml
   tags:
     - setup-all
     - setup-jellyfin

 - import_tasks: jellyseer.yml
   tags:
     - setup-all
     - setup-jellyfin
     - setup-jellyseerr
