---

- name: Ensure transmission container is created and running
  docker_container:
    name: "{{ transmission_container_name }}"
    image: "{{ transmission_container_image }}"
    env:
      PGID: "{{ container_user | string }}"
      PUID: "{{ container_user | string }}"
      TZ: "{{ container_tz }}"
      TRANSMISSION_PEER_PORT: "{{ wireguard_forwarded_port | string }}"
      TRANSMISSION_WEB_HOME: "/transmission-web-control/"
    volumes: "{{ transmission_volumes_full_paths }}"
    network_mode: "{{ servarr_containers_network_mode }}"
    restart_policy: always
